WIP: Support S-Expression syntax in stubs
Andriamanitra/clash pull request #65
Opened 2024-04-28 07:52 UTC by ellnix

Languages like lisp, clojure, or webassembly have [S-Expression](https://en.wikipedia.org/wiki/S-expression) syntax which cannot be generated from the current way we store stubs.

2024-05-07 13:45 UTC, Andriamanitra requested changes
I think the preprocessors and the 'ad-hoc' commands they introduce are a messy solution, but it works well for now and I don't have any better ideas.

The only thing keeping this from getting merged right now is that the `s-expression` preprocessor should be renamed to something more accurate (as discussed on Discord the other day).

I'd be fine with any of these suggestions (or something similar):
* `lisp-like`
* `batch-read-with-lexical-scope`
* `read-batch-with-explicit-scope`

2024-05-07 13:47 UTC, ellnix commented
>     * `read-batch-with-explicit-scope`

This is probably my favorite, since it hints that this preprocessor is why there is a read_batch template.

2024-05-08 12:44 UTC, daxida approved these changes
Everything seems fine to me :+1:

2024-05-08 12:44 UTC, daxida commented on src/stub/preprocessor/lisp_like.rs
> +/// Edit Stub to allow for rendering lisp-like syntax
Final dot after "syntax" to be consistent :D

2024-05-08 12:45 UTC, ellnix commented on src/stub/preprocessor/lisp_like.rs
> +/// Edit Stub to allow for rendering lisp-like syntax
You got me xD

2024-05-08 16:21 UTC, Andriamanitra approved these changes

2024-05-08 16:25 UTC, merged